# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 19:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelist', '0003_auto_20161005_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='law',
            name='date_last_revision',
        ),
        migrations.AddField(
            model_name='law',
            name='date_publication',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 5, 19, 37, 38, 606185), verbose_name=b'Versi\xc3\xb3n de fecha'),
        ),
    ]
