# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 19:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelist', '0004_auto_20161005_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='date_publication',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 5, 19, 44, 14, 446055), verbose_name=b'Versi\xc3\xb3n de fecha'),
        ),
    ]
