# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 19:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelist', '0005_auto_20161005_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='date_publication',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 5, 19, 50, 32, 193780), verbose_name=b'Versi\xc3\xb3n de fecha'),
        ),
    ]
