# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelist', '0007_auto_20161005_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='textContract',
            field=models.TextField(default=b''),
        ),
    ]
