# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelist', '0008_contract_textcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='isUpdated',
            field=models.BooleanField(default=True),
        ),
    ]
