# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('changelist', '0009_contract_isupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='dateLastRevision',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
