# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('changelist', '0010_contract_datelastrevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelaw',
            name='text',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='articlelaw',
            name='version',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
